# Site settings
title: Pepper Curry: Design &amp; Illustration
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Pepper Curry is a designer and illustrator living and working in Wellington, New Zealand. Find a collection of experiments and works here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.peppercurry.com" # the base hostname & protocol for your site
twitter_username: sempercapsicum
github_username:  sempercapsicum

# Build settings
markdown: kramdown
